version: "3"
services:
  web:
    container_name: app
    build: .
    ports:
      - "8100:8100"
    environment:
      - NODE_ENV=docker
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - "../:/app/static"
    networks:
      - webnet 
networks:
  webnet: